BronzebeardQuestChains = {
    ["dk-q1"] = {
        id = "dk-q1",
        name = "Monsters With Noble Intentions",
        description = "First quest of the Cain Estate chain – help Riscell Cain deal with unusual friendly undead in the manor.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = nil,
        next = "dk-q2",
    },

    ["dk-q2"] = {
        id = "dk-q2",
        name = "Restless Family Members",
        description = "Put the troubled Cain family spirits to rest in the estate.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q1",
        next = "dk-q3",
    },

    ["dk-q3"] = {
        id = "dk-q3",
        name = "I'm Home",
        description = "Escort Riscell Cain back into his family home and secure it.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q2",
        next = "dk-q4",
    },

    ["dk-q4"] = {
        id = "dk-q4",
        name = "An Unspeakable Secret",
        description = "Discover the hidden secret lurking in the Cain Manor cellar.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q3",
        next = "dk-q5",
    },

    ["dk-q5"] = {
        id = "dk-q5",
        name = "A Noble Heritage",
        description = "Learn about the Cain family history and Priscilla Cain's dark past.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q4",
        next = "dk-q6",
    },

    ["dk-q6"] = {
        id = "dk-q6",
        name = "The Friends We Make Along The Way",
        description = "Befriend an unlikely ally (the infernal Sidragaso's offspring) during the estate quest line.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q5",
        next = "dk-q7",
    },

    ["dk-q7"] = {
        id = "dk-q7",
        name = "The True Heir of the Cains",
        description = "Conclude the Cain Manor storyline by confronting the legacy of Priscilla's son and restoring the estate.",
        zoneId = "deathknell",
        x = 47,
        y = 52,
        faction = "horde",
        prev = "dk-q6",
        next = "dk-q8",
    },

    ["dk-q8"] = {
        id = "dk-q8",
        name = "Apothecary Flemer",
        description = "Assist Apothecary Flemer with a special task after securing the Cain Estate (final quest in the chain).",
        zoneId = "deathknell",
        x = 46,
        y = 57.99999999999999,
        faction = "horde",
        prev = "dk-q7",
        next = nil,
    },

    ["vo-q1"] = {
        id = "vo-q1",
        name = "Those Who Fell",
        description = "Investigate the fate of fallen warriors near Zeb'Goro and lay them to rest (kicking off the Zeb'Goro quest chain).",
        zoneId = "valley-of-trials",
        x = 57.99999999999999,
        y = 74,
        faction = "horde",
        prev = nil,
        next = "vo-q2",
    },

    ["vo-q2"] = {
        id = "vo-q2",
        name = "The Way is Shut",
        description = "Seal a cavern entrance in the Sinister Lair to contain the restless spirits within.",
        zoneId = "valley-of-trials",
        x = 60,
        y = 69,
        faction = "horde",
        prev = "vo-q1",
        next = "vo-q3",
    },

    ["vo-q3"] = {
        id = "vo-q3",
        name = "Unease Makes Tongues Wag",
        description = "Gather information from nervous villagers in Zeb'Goro about the dark presence haunting the area.",
        zoneId = "valley-of-trials",
        x = 56.99999999999999,
        y = 80,
        faction = "horde",
        prev = "vo-q2",
        next = "vo-q4",
    },

    ["vo-q4"] = {
        id = "vo-q4",
        name = "A Door Left Ajar",
        description = "Enter the Sinister Lair cavern and confront the initial waves of Loa-possessed creatures.",
        zoneId = "valley-of-trials",
        x = 55.00000000000001,
        y = 78,
        faction = "horde",
        prev = "vo-q3",
        next = "vo-q5",
    },

    ["vo-q5"] = {
        id = "vo-q5",
        name = "The Sinister Triad",
        description = "Learn about the three death Loa (Dambala, Shadra, Hireek) forming the Sinister Triad and their plot in the troll death-realm.",
        zoneId = "valley-of-trials",
        x = 53,
        y = 82,
        faction = "horde",
        prev = "vo-q4",
        next = "vo-q6",
    },

    ["vo-q6"] = {
        id = "vo-q6",
        name = "So That He May Hear Again",
        description = "Collect ritual components in the Sinister Den to commune with Bwonsamdi or Mueh'zala for guidance against the Triad.",
        zoneId = "valley-of-trials",
        x = 53,
        y = 82,
        faction = "horde",
        prev = "vo-q5",
        next = "vo-q7",
    },

    ["vo-q7"] = {
        id = "vo-q7",
        name = "A Sinister Ritual",
        description = "Disrupt the triad's ritual in the heart of the Sinister Den, where loa spirits have manifested.",
        zoneId = "valley-of-trials",
        x = 52,
        y = 76,
        faction = "horde",
        prev = "vo-q6",
        next = "vo-q8",
    },

    ["vo-q8"] = {
        id = "vo-q8",
        name = "Innocents for Sinners",
        description = "Rescue captive villagers intended as sacrifices to the Sinister Triad, concluding the Zeb'Goro storyline.",
        zoneId = "valley-of-trials",
        x = 52,
        y = 76,
        faction = "horde",
        prev = "vo-q7",
        next = nil,
    },

    ["rc-q1"] = {
        id = "rc-q1",
        name = "Death and Tribute",
        description = "Deliver a bone-tribute to the Great Hyena on Morriga's behalf, proving your willingness to follow the Hyena's cruel wisdom.",
        zoneId = "camp-narache",
        x = 43,
        y = 76,
        faction = "horde",
        prev = nil,
        next = "rc-q2",
    },

    ["rc-q2"] = {
        id = "rc-q2",
        name = "Death and Exile",
        description = "Visit Morriga at her banishment site on the mesa's edge; help her cope with exile and plan against her father.",
        zoneId = "camp-narache",
        x = 40,
        y = 79,
        faction = "horde",
        prev = "rc-q1",
        next = "rc-q3",
    },

    ["rc-q3"] = {
        id = "rc-q3",
        name = "To Whom I Devote",
        description = "Witness Morriga's dark pact ceremony with the Great Hyena spirit; understand to whom she devotes her loyalty and why.",
        zoneId = "camp-narache",
        x = 42,
        y = 81,
        faction = "horde",
        prev = "rc-q2",
        next = "rc-q4",
    },

    ["rc-q4"] = {
        id = "rc-q4",
        name = "Death and Dishonor",
        description = "Sabotage Chief Malgorm Hollowhoof's standing: perform acts that bring dishonor to him in the eyes of his Grimtotem followers.",
        zoneId = "camp-narache",
        x = 45,
        y = 75,
        faction = "horde",
        prev = "rc-q3",
        next = "rc-q5",
    },

    ["rc-q5"] = {
        id = "rc-q5",
        name = "Fighting Over Carrion",
        description = "Incite infighting among Malgorm's lieutenants by making them literally fight over carrion (a test of strength favored by the Hyena).",
        zoneId = "camp-narache",
        x = 47,
        y = 72,
        faction = "horde",
        prev = "rc-q4",
        next = "rc-q6",
    },

    ["rc-q6"] = {
        id = "rc-q6",
        name = "Death and Justice",
        description = "Assist Morriga in delivering justice to Malgorm for his tyranny – likely involving defeating his champions or exposing his crimes.",
        zoneId = "camp-narache",
        x = 44,
        y = 68,
        faction = "horde",
        prev = "rc-q5",
        next = "rc-q7",
    },

    ["rc-q7"] = {
        id = "rc-q7",
        name = "Death by Laughter",
        description = "The final showdown in Three Totem Village. Use the Great Hyena's power (symbolized by mocking laughter) to bring down Malgorm Hollowhoof.",
        zoneId = "camp-narache",
        x = 39,
        y = 77,
        faction = "horde",
        prev = "rc-q6",
        next = nil,
    },

    ["ns-q1"] = {
        id = "ns-q1",
        name = "Bookworm",
        description = "Search the ruins of Northshire for an old tome of dark knowledge (starts the Old Northshire Village quest arc).",
        zoneId = "northshire",
        x = 43,
        y = 57.99999999999999,
        faction = "alliance",
        prev = nil,
        next = "ns-q2",
    },

    ["ns-q2"] = {
        id = "ns-q2",
        name = "Knowledge Corrupts",
        description = "Uncover Sister Sitis's hidden teachings; the more you learn, the more the corruption of the Abbey's past reveals itself.",
        zoneId = "northshire",
        x = 45,
        y = 55.00000000000001,
        faction = "alliance",
        prev = "ns-q1",
        next = "ns-q3",
    },

    ["ns-q3"] = {
        id = "ns-q3",
        name = "The Ruins of Northshire",
        description = "Explore the forsaken village outside the Abbey. Collect clues of the scandal and betrayal that led to its curse.",
        zoneId = "northshire",
        x = 47,
        y = 60,
        faction = "alliance",
        prev = "ns-q2",
        next = "ns-q4",
    },

    ["ns-q4"] = {
        id = "ns-q4",
        name = "Accursed Sisterhood",
        description = "Confront the restless spirits of Sister Sitis's former apprentices, who linger in the village under a dark curse.",
        zoneId = "northshire",
        x = 50,
        y = 64,
        faction = "alliance",
        prev = "ns-q3",
        next = "ns-q5",
    },

    ["ns-q5"] = {
        id = "ns-q5",
        name = "The Saddest Among Us",
        description = "Aid a sorrowful ghost in the ruins (possibly a victim of Sitis's experiments) to find peace.",
        zoneId = "northshire",
        x = 52,
        y = 66,
        faction = "alliance",
        prev = "ns-q4",
        next = "ns-q6",
    },

    ["ns-q6"] = {
        id = "ns-q6",
        name = "Words That Shepherd Madness",
        description = "Collect the scattered pages of Sister Sitis's teachings (\"the murmurs of the spring\") around Shadewell Spring's tower.",
        zoneId = "northshire",
        x = 59,
        y = 70,
        faction = "alliance",
        prev = "ns-q5",
        next = "ns-q7",
    },

    ["ns-q7"] = {
        id = "ns-q7",
        name = "The Threat Swept Downstream",
        description = "Conclude the chain by thwarting the final ritual at Shadewell Spring – where Sister Sitis's influence taints the waters and drives initiates mad.",
        zoneId = "northshire",
        x = 61,
        y = 72,
        faction = "alliance",
        prev = "ns-q6",
        next = nil,
    },

    ["sg-q1"] = {
        id = "sg-q1",
        name = "The Carrion Road",
        description = "Follow a trail of carcasses leading to the Eyrie cult's hideout (start of the Eyrie quest line).",
        zoneId = "shadowglen",
        x = 64,
        y = 25,
        faction = "alliance",
        prev = nil,
        next = "sg-q2",
    },

    ["sg-q2"] = {
        id = "sg-q2",
        name = "The Sister Who Never Returned",
        description = "Investigate the fate of a missing novice druid (presumed taken by the Vulture cult) – eventually discover she's part of the cult's ossuary.",
        zoneId = "shadowglen",
        x = 66,
        y = 19,
        faction = "alliance",
        prev = "sg-q1",
        next = "sg-q3",
    },

    ["sg-q3"] = {
        id = "sg-q3",
        name = "Finding the Good Meat",
        description = "Gather \"good meat\" (fresh carcasses) to use as bait or offering – the cult tests recruits by how well they can procure carrion.",
        zoneId = "shadowglen",
        x = 62,
        y = 30,
        faction = "alliance",
        prev = "sg-q2",
        next = "sg-q4",
    },

    ["sg-q4"] = {
        id = "sg-q4",
        name = "Restless Entrails",
        description = "Slay animated, writhing entrails in the Moonlit Ossuary (the cult's charnel ground) – put to rest the remains of those who failed the cult's trials.",
        zoneId = "shadowglen",
        x = 68,
        y = 22,
        faction = "alliance",
        prev = "sg-q3",
        next = "sg-q5",
    },

    ["sg-q5"] = {
        id = "sg-q5",
        name = "Transubstantiating the Flesh",
        description = "Assist Aegya's former ally in performing a counter-ritual to sanctify (or transmute) the corrupted flesh the cult has been feasting on.",
        zoneId = "shadowglen",
        x = 70,
        y = 18,
        faction = "alliance",
        prev = "sg-q4",
        next = "sg-q6",
    },

    ["sg-q6"] = {
        id = "sg-q6",
        name = "Communion Banquet",
        description = "Infiltrate the cult's grand feast where aspirants consume prepared flesh to commune with the Great Vulture. Survive their brutal proving combat during the banquet.",
        zoneId = "shadowglen",
        x = 72,
        y = 20,
        faction = "alliance",
        prev = "sg-q5",
        next = "sg-q7",
    },

    ["sg-q7"] = {
        id = "sg-q7",
        name = "A Trail of Petals",
        description = "Track Aegya's escape route (marked by blood-stained petals) after the cult's defeat, to ensure any remaining threat is eliminated (concludes the Eyrie quest line).",
        zoneId = "shadowglen",
        x = 59,
        y = 37,
        faction = "alliance",
        prev = "sg-q6",
        next = nil,
    },

    ["cv-q1"] = {
        id = "cv-q1",
        name = "Smoke On The Wind",
        description = "Groldha in Anvilmar saw smoke on a mountainside – investigate the source. Leads to finding the goblin Crash Site and starts the Radiant Ones storyline.",
        zoneId = "coldridge-valley",
        x = 25,
        y = 60,
        faction = "alliance",
        prev = nil,
        next = "cv-q2",
    },

    ["cv-q2"] = {
        id = "cv-q2",
        name = "A Promising Path",
        description = "Follow clues from the crash to track the goblin survivors or their cargo. Hints at a secret meeting with mysterious allies (the \"Radiant\" faction).",
        zoneId = "coldridge-valley",
        x = 28.000000000000004,
        y = 55.00000000000001,
        faction = "alliance",
        prev = "cv-q1",
        next = "cv-q3",
    },

    ["cv-q3"] = {
        id = "cv-q3",
        name = "A Fitting Disguise",
        description = "Craft or acquire a disguise to sneak into Radiance Town. The Radiant Ones are paranoid, so you must appear as one of their irradiated members (leper gnome/dwarf).",
        zoneId = "coldridge-valley",
        x = 80,
        y = 22,
        faction = "alliance",
        prev = "cv-q2",
        next = "cv-q4",
    },

    ["cv-q4"] = {
        id = "cv-q4",
        name = "His Radiant Majesty",
        description = "Gain an audience with the leader of the Radiant Ones (self-titled \"His Radiant Majesty\"). Discover his plan to spread a radiation-based \"enlightenment\" at a terrible cost.",
        zoneId = "coldridge-valley",
        x = 78,
        y = 17,
        faction = "alliance",
        prev = "cv-q3",
        next = "cv-q5",
    },

    ["cv-q5"] = {
        id = "cv-q5",
        name = "Sever the Right Hand",
        description = "Assassinate or neutralize the Radiant Ones' second-in-command (the leader's \"Right Hand\"). This will sow chaos in Radiance Town's hierarchy.",
        zoneId = "coldridge-valley",
        x = 80,
        y = 15,
        faction = "alliance",
        prev = "cv-q4",
        next = "cv-q6",
    },

    ["cv-q6"] = {
        id = "cv-q6",
        name = "Soaking The Masses",
        description = "Sabotage the Radiant Ones' radiation devices (\"soakers\") that they use to irradiate new initiates. This undermines their ability to create more leper followers.",
        zoneId = "coldridge-valley",
        x = 81,
        y = 20,
        faction = "alliance",
        prev = "cv-q5",
        next = "cv-q7",
    },

    ["cv-q7"] = {
        id = "cv-q7",
        name = "Deciphering Radiation",
        description = "Collect data from the Radiant Ones' lab to understand their experiments. Turn this information over to the gnomish engineers in Ironforge for further study (concludes the chain).",
        zoneId = "coldridge-valley",
        x = 72,
        y = 18,
        faction = "alliance",
        prev = "cv-q6",
        next = nil,
    },

    ["ds-q1"] = {
        id = "ds-q1",
        name = "Gelkis Alliance",
        description = "New Alliance quest to gain Gelkis centaur trust: \"If you choose to ally with the Gelkis then slay their most hated rival, the Magram... After you earn respect, meet Uthek the Wise in southwest Desolace.\"",
        zoneId = "desolace",
        x = 36,
        y = 87,
        faction = "alliance",
        prev = nil,
        next = nil,
    },

    ["ds-q2"] = {
        id = "ds-q2",
        name = "Magram Alliance",
        description = "New Alliance quest to gain Magram centaur trust: \"If you choose to ally with the Magram then slay their foes, the Gelkis... earn respect then meet Warug at Magram Village in southeast Desolace.\"",
        zoneId = "desolace",
        x = 72,
        y = 77,
        faction = "alliance",
        prev = nil,
        next = nil,
    },

    ["bb-wet-q1"] = {
        id = "bb-wet-q1",
        name = "Mercenary's Down Payment",
        description = "Speak with Krazzle Sparkplug at the new Camp Blackwood. He requires you to prove your worth before offering the camp's mercenary contracts.",
        zoneId = "wetlands",
        x = 48,
        y = 52,
        faction = "neutral",
        prev = nil,
        next = "bb-wet-q2",
    },

    ["bb-wet-q2"] = {
        id = "bb-wet-q2",
        name = "No Questions Asked",
        description = "Krazzle Sparkplug wants you to intercept a rival caravan supply shipment near the road. The goods are to be 'reallocated' to Camp Blackwood.",
        zoneId = "wetlands",
        x = 48,
        y = 52,
        faction = "neutral",
        prev = "bb-wet-q1",
        next = "bb-wet-q3",
    },

    ["marker-1765406063327-ddik8zl"] = {
        id = "marker-1765406063327-ddik8zl",
        name = "Archmage Xylem",
        description = "New questline from archmage Xylem for the polymorph: pig glyph",
        zoneId = "azshara",
        x = 29.877591551494888,
        y = 40.51232238139,
        faction = nil,
        prev = nil,
        next = nil,
    },

}

-- (La inyección a SKquests_DetailDB se hace en SKquests_UI.lua, con nombres
--  limpios y coords de azerothhub. Este archivo solo define la tabla de datos.)
