-- SKquests Language Module
-- Supports English and Spanish

SKquests_Localization = {
    currentLanguage = "esES",  -- idioma por defecto

    languages = {
        enUS = true,
        esES = true,
    }
}

-- English translations
SKquests_Localization.enUS = {
    QUEST_TITLE = "Quest",
    OBJECTIVES = "Objectives",
    DESCRIPTION = "Description",
    START_END = "Start / Turn in",
    REWARDS = "Rewards",
    FIXED_REWARDS = "Guaranteed:",
    CHOICE_REWARDS = "Choose one:",
    WOWHEAD = "Wowhead",
    WOWHEAD_LINK = "Wowhead link",
    COPY = "Copy",
    QUEST_DETAILS = "Quest details",
    QUEST_CHAIN = "Quest chain",
    TAB_GUIDE = "Guide",
    TAB_QUESTLOG = "Quest Log",
    TAB_QUESTS = "Quests",
    TAB_ZONES = "Zones",
    TAB_SETTINGS = "Settings",
    TAB_ABOUT = "About",
    TITLE_GUIDE = "SKquests - %s Leveling Guide",
    TITLE_QUESTLOG = "SKquests - Quest Log",
    TITLE_EXPLORER = "SKquests - Quest Explorer",
    TITLE_ZONES = "SKquests - Zones of Azeroth",
    TITLE_ABOUT = "SKquests - About",
    SETTINGS_TITLE = "SKquests - Settings",
    ABOUT_TITLE = "About SKquests",
    ALLIANCE = "Alliance",
    HORDE = "Horde",
    COUNT_FOUND = "(%d quests found)",
    COUNT_ACTIVE = "(%d active quests)",
    COUNT_STEPS = "(%d steps)",
    COUNT_ZONES = "(%d active zones)",
    THEME_LBL = "Appearance theme:",
    THEME_DARK = "Dark",
    THEME_LIGHT = "Light",
    EDIT_THEME = "Edit Theme",
    OPACITY_LBL = "Window opacity:",
    LOCK_WINDOW = "Lock window movement",
    GUIDE_FORMULA = "Current guide formula:",
    WIDTH_LBL = "Window width:",
    HEIGHT_LBL = "Window height:",
    ZONES_BTN = "Zones",
    ALL_ZONES = "All",
    NO_QUEST_SELECTED = "No quest selected",
    SELECT_QUEST_HINT = "Select a quest from the left panel.",
    NO_DETAILS = "No details.",
    ZONE_META = "Zone: |cffffffff%s|r",
    MAP_HINT = "Wheel: zoom - Drag: pan - Click: reset",
    MAP_START = "Quest start",
    ROW_QUESTID = "Quest ID",
    ROW_MINLVL = "Required level",
    ROW_STATUS = "Status",
    START_NPC = "START (NPC)",
    START_GO = "START (Object)",
    END_NPC = "TURN IN (NPC)",
    END_GO = "TURN IN (Object)",
    UNKNOWN = "Unknown",
    LVL_ABBR = "Lv",
    ST_ACTIVE = "Active",
    ST_DONE = "Completed",
    ST_NOT_STARTED = "Not started",
    ST_READY = "Ready to turn in",
    ST_PROGRESS = "In progress",
    STARTS_WITH = "Starts with:",
    ENDS_WITH = "Turn in to:",
    ACTIVE_NO_OBJ = "Active quest. (No objectives recorded)",
    LOADED_FROM_DB = "Quest details loaded from the database.",
    NOT_IN_DB = "This quest is not registered in SKquests' local database.",
    MAP_END = "Turn in",
    STEP_OBJECTIVE = "Step objective",
    LANG_CHANGED = "Language changed to ",
    STEP = "Step",
    OF = "of",
    NEXT_QUEST = "Next Quest",
    PREVIOUS_QUEST = "Previous Quest",
    QUEST_OBJECTIVES = "Quest Objectives",
    WHAT_TO_DO = "What to do",
    LANGUAGE = "Language",
    SETTINGS = "Settings",
    ACCEPT = "Accept",
    CLOSE = "Close",
    TRACK = "Track",
    HELP = "Help",
    COMMANDS = "Commands",
    NOT_ASSIGNED = "Not assigned",
    NO_INFORMATION = "No information available",
    CLICK_FOR_WOWHEAD = "Click to open on Wowhead",
    QUESTIE_STATUS = "Questie Status",
    SHOW_TITLE = "Show quest title",
    SHOW_IMAGE = "Show map image",
    AUTO_MINIMIZE = "Auto minimize in combat",
    QUESTIE_INTEGRATION = "Questie integration",
    IMAGE_SIZE = "Image size",
    TEXT_SIZE = "Text size",
    OPACITY = "Opacity",
    GENERAL = "General",
    APPEARANCE = "Appearance",
    INFORMATION = "Information",
    SMALL = "Small",
    MEDIUM = "Medium",
    LARGE = "Large",
    NORMAL = "Normal",
}

-- Spanish translations
SKquests_Localization.esES = {
    QUEST_TITLE = "Misión",
    OBJECTIVES = "Objetivos",
    DESCRIPTION = "Descripción",
    START_END = "Empezar / Entregar",
    REWARDS = "Recompensas",
    FIXED_REWARDS = "Aseguradas:",
    CHOICE_REWARDS = "A elección:",
    WOWHEAD = "Wowhead",
    WOWHEAD_LINK = "Enlace Wowhead",
    COPY = "Copiar",
    QUEST_DETAILS = "Detalles de quest",
    QUEST_CHAIN = "Cadena de quests",
    TAB_GUIDE = "Guía",
    TAB_QUESTLOG = "Quest Log",
    TAB_QUESTS = "Quests",
    TAB_ZONES = "Zonas",
    TAB_SETTINGS = "Ajustes",
    TAB_ABOUT = "Acerca de",
    TITLE_GUIDE = "SKquests - Guía Leveo %s",
    TITLE_QUESTLOG = "SKquests - Quest Log",
    TITLE_EXPLORER = "SKquests - Explorador de Misiones",
    TITLE_ZONES = "SKquests - Zonas de Azeroth",
    TITLE_ABOUT = "SKquests - Acerca de",
    SETTINGS_TITLE = "SKquests - Configuración",
    ABOUT_TITLE = "Acerca de SKquests",
    ALLIANCE = "Alianza",
    HORDE = "Horda",
    COUNT_FOUND = "(%d misiones encontradas)",
    COUNT_ACTIVE = "(%d misiones activas)",
    COUNT_STEPS = "(%d pasos)",
    COUNT_ZONES = "(%d zonas activas)",
    THEME_LBL = "Tema de apariencia:",
    THEME_DARK = "Oscuro",
    THEME_LIGHT = "Claro",
    EDIT_THEME = "Editar Tema",
    OPACITY_LBL = "Opacidad de ventana:",
    LOCK_WINDOW = "Bloquear movimiento de ventana",
    GUIDE_FORMULA = "Fórmula de guía actual:",
    WIDTH_LBL = "Ancho de ventana:",
    HEIGHT_LBL = "Alto de ventana:",
    ZONES_BTN = "Zonas",
    ALL_ZONES = "Todas",
    NO_QUEST_SELECTED = "Ninguna misión seleccionada",
    SELECT_QUEST_HINT = "Selecciona una misión del panel izquierdo.",
    NO_DETAILS = "No hay detalles.",
    ZONE_META = "Zona: |cffffffff%s|r",
    MAP_HINT = "Rueda: zoom - Arrastrar: mover - Clic: restablecer",
    MAP_START = "Inicio de misión",
    ROW_QUESTID = "ID de Quest",
    ROW_MINLVL = "Nivel requerido",
    ROW_STATUS = "Estado",
    START_NPC = "INICIO (NPC)",
    START_GO = "INICIO (Objeto)",
    END_NPC = "ENTREGA (NPC)",
    END_GO = "ENTREGA (Objeto)",
    UNKNOWN = "Desconocido",
    LVL_ABBR = "Nv",
    ST_ACTIVE = "Activa",
    ST_DONE = "Completada",
    ST_NOT_STARTED = "No iniciada",
    ST_READY = "Lista para entregar",
    ST_PROGRESS = "En progreso",
    STARTS_WITH = "Inicia con:",
    ENDS_WITH = "Entrega a:",
    ACTIVE_NO_OBJ = "Misión activa. (Sin objetivos registrados)",
    LOADED_FROM_DB = "Detalles de misión cargados desde la base de datos.",
    NOT_IN_DB = "Esta misión no se encuentra registrada en la base de datos local de SKquests.",
    MAP_END = "Entrega",
    STEP_OBJECTIVE = "Objetivo del Paso",
    LANG_CHANGED = "Idioma cambiado a ",
    STEP = "Paso",
    OF = "de",
    NEXT_QUEST = "Siguiente Misión",
    PREVIOUS_QUEST = "Misión Anterior",
    QUEST_OBJECTIVES = "Objetivos de la Misión",
    WHAT_TO_DO = "Qué hacer",
    LANGUAGE = "Idioma",
    SETTINGS = "Configuración",
    ACCEPT = "Aceptar",
    CLOSE = "Cerrar",
    TRACK = "Rastrear",
    HELP = "Ayuda",
    COMMANDS = "Comandos",
    NOT_ASSIGNED = "No asignado",
    NO_INFORMATION = "Información no disponible",
    CLICK_FOR_WOWHEAD = "Clic para abrir en Wowhead",
    QUESTIE_STATUS = "Estado Questie",
    SHOW_TITLE = "Mostrar título de misión",
    SHOW_IMAGE = "Mostrar imagen del mapa",
    AUTO_MINIMIZE = "Minimizar automático en combate",
    QUESTIE_INTEGRATION = "Integración con Questie",
    IMAGE_SIZE = "Tamaño de imagen",
    TEXT_SIZE = "Tamaño de texto",
    OPACITY = "Opacidad",
    GENERAL = "General",
    APPEARANCE = "Apariencia",
    INFORMATION = "Información",
    SMALL = "Pequeño",
    MEDIUM = "Mediano",
    LARGE = "Grande",
    NORMAL = "Normal",
}

function SKquests_Localization:SetLanguage(lang)
    if self.languages[lang] then
        self.currentLanguage = lang
        return true
    end
    return false
end

function SKquests_Localization:Get(key)
    local translations = self[self.currentLanguage]
    if translations and translations[key] then
        return translations[key]
    end
    local englishTranslations = self.enUS
    if englishTranslations and englishTranslations[key] then
        return englishTranslations[key]
    end
    return key
end

-- Shorthand function
function L(key)
    return SKquests_Localization:Get(key)
end
